using RR.Agent.Model.Enums;

namespace RR.Agent.Model.Dtos;

/// <summary>
/// Represents the result of executing a Python script.
/// </summary>
public sealed class PythonExecutionResult
{
    /// <summary>
    /// The overall execution result status.
    /// </summary>
    public ExecutionResult Result { get; set; }

    /// <summary>
    /// The process exit code. 0 typically indicates success.
    /// </summary>
    public int ExitCode { get; set; }

    /// <summary>
    /// The captured standard output from the script.
    /// </summary>
    public string StandardOutput { get; set; } = string.Empty;

    /// <summary>
    /// The captured standard error from the script.
    /// </summary>
    public string StandardError { get; set; } = string.Empty;

    /// <summary>
    /// The total time taken to execute the script.
    /// </summary>
    public TimeSpan ExecutionTime { get; set; }

    /// <summary>
    /// The path to the executed script file.
    /// </summary>
    public string? ScriptPath { get; set; }

    /// <summary>
    /// List of files generated by the script execution.
    /// </summary>
    public List<string> GeneratedFiles { get; set; } = [];

    /// <summary>
    /// Error message if the execution failed before the script could run.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Creates a successful execution result.
    /// </summary>
    public static PythonExecutionResult Success(string stdout, string stderr, TimeSpan duration, string? scriptPath = null) => new()
    {
        Result = ExecutionResult.Success,
        ExitCode = 0,
        StandardOutput = stdout,
        StandardError = stderr,
        ExecutionTime = duration,
        ScriptPath = scriptPath
    };

    /// <summary>
    /// Creates a failed execution result.
    /// </summary>
    public static PythonExecutionResult Failure(int exitCode, string stdout, string stderr, TimeSpan duration, string? scriptPath = null) => new()
    {
        Result = ExecutionResult.Failure,
        ExitCode = exitCode,
        StandardOutput = stdout,
        StandardError = stderr,
        ExecutionTime = duration,
        ScriptPath = scriptPath
    };

    /// <summary>
    /// Creates an error result when execution could not start.
    /// </summary>
    public static PythonExecutionResult Error(string errorMessage) => new()
    {
        Result = ExecutionResult.Error,
        ExitCode = -1,
        ErrorMessage = errorMessage
    };

    /// <summary>
    /// Creates a timeout result.
    /// </summary>
    public static PythonExecutionResult Timeout(TimeSpan duration, string? scriptPath = null) => new()
    {
        Result = ExecutionResult.Timeout,
        ExitCode = -1,
        ExecutionTime = duration,
        ScriptPath = scriptPath,
        ErrorMessage = $"Script execution exceeded timeout of {duration.TotalSeconds} seconds"
    };
}
